### ISSUE TITLE
Initial setup

### ISSUE THREAD

**Issue by PetrBuk** [PetrBuk/4IT428-vse-go-newsletter#1]
Create initial project setup
- [x] Setup GitHub repository
- [x] Basic folder structure
- [x] PostgreSQL database
- [x] Supabase authenticator middleware

**Comment by vokounovaeliska** [comment]
Just notes from the exercise:
- Supabase for database (PostgreSQL)
- Cloud run for deploy

Should I set up a database?

**Comment by PetrBuk** [comment]
Already done ;-)

**Comment by vokounovaeliska** [comment]
What about adding contribors? That should be a task. Reopen please.

**Comment by PetrBuk** [comment]
@vokounovaeliska  What do you mean, contribors? :o

**Comment by vokounovaeliska** [comment]
*contributors

but it's fine now. Thanks, Petr. :)
