### ISSUE TITLE
Publishing

### ISSUE THREAD

**Issue by PetrBuk** [PetrBuk/4IT428-vse-go-newsletter#5]
Endpoints:
- [x] Create post in db
- [x] Create a post
- [x] Edit a post
- [x] Delete a post
- [x] Get
- [x] GetList
- [x] Publish a post 

OR (Maybe preffered)

- [x] Just publish endpoint, which saves the post to the DB and sends the emails
- [x] send email to subscribers

Publishing a post means sending it in an email to all subscribers of related Newsletter.

**Comment by vokounovaeliska** [comment]
I think this is also done! I'm closing this issue. 👌 thank you @PetrBuk , @HonzaDoly
